# Metrics window size
metrics.window=10000
# Report interval, in milliseconds
report.interval=1000
# TimeUnit to use for reporting rate metrics
report.ratetimeunit = SECONDS
# TimeUnit to use for reporting duration metrics
report.durationtimeunit = MILLISECONDS

# Number of records to send in total
recordstream.records = 9223372036854775807
# Delay between sending records, in ISO-8601 duration (also referred to as "period") format
delay.duration=PT0S

# Number of clients to use
initiator.count = 1
# Number of EventLoops to distribute clients between
initiator.eventloopcount = 1
# Maximum number of times clients should retry to connect
initiator.retryconnectioncount = 3
# Maximum number of times clients should retry to send a record
initiator.retrytransmissioncount = 3

# Prometheus endpoint port
prometheus.port=8080

# Appname used in RELP record
syslog.appname=appName
# Hostname used in RELP record
syslog.hostname=localhost

# RELP Server target address
socket.hostname=localhost
# Relp Server target port
socket.port=8080
# RELP Server reconnect interval, in milliseconds
timeout.open=1000
# RELP Server resend interval, in milliseconds
timeout.payload=1000

# Boolean flag to enable or disable TLS, defaults to disabled
transport.tls=false
# TLS path to keystore
transport.keystorepath="tls/keystore.jks"
# TLS keystore password
transport.keystorepassword=changeit
# TLS path to truststore
transport.truststorepath="tls/truststore.jks"
# TLS truststore password
transport.truststorepassword=changeit
# TLS protocol to be used
transport.protocol=TLSv1.3

